services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $isDebug: '%kernel.debug%'

    Torr\MenuBundle\:
        resource: '../../*'
        exclude: '../../{Exception,Node,Resources,Voter,TorrMenuBundle.php}'

    Torr\MenuBundle\Renderer\MenuRenderer:
        $visitors: !tagged torr.menu.visitor

    Torr\MenuBundle\Visitor\CoreVisitor:
        tags:
            - { name: torr.menu.visitor, priority: -1000 }

    Torr\MenuBundle\Visitor\TranslationVisitor:
        tags:
            - { name: torr.menu.visitor, priority: -1100 }

    Torr\MenuBundle\Visitor\VoterVisitor:
        arguments:
            $voters: !tagged torr.menu.voter
        tags:
            - { name: torr.menu.visitor, priority: -1500 }
