services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\MenuBundle\:
        resource: ../src/*
        exclude:
            - ../src/Exception
            - ../src/Item
            - ../src/Render/Options
            - ../src/RouteTree/Collection
            - ../src/RouteTree/Exception
            - ../src/RouteTree/Options
            - ../src/RouteTree/Tree
            - ../src/TorrMenuBundle.php

    Torr\MenuBundle\RouteTree\Loader\RouteTreeLoader:
        $configCacheFactory: '@config_cache_factory'
        $cacheDir: '%kernel.cache_dir%'
